### ISSUE TITLE
API connection problem

### ISSUE THREAD

**Issue by ghost** [din14970/elabftwqrprint#10]
Good day.
I'm trying to install your application for elabFTW to print QR codes with Brother QL-810w printer.
ElabFTW is installed in Docker container on Hyper-V machine.
I followed your manual, but after launching configure_elabftw, specifying URL and API token, the following error occures:

Traceback (most recent call last):
  File "/root/.local/bin/configure_elabftw", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/elabftwqrprint/configure_elabftw.py", line 40, in main
    manager.get_status()
  File "/root/.local/lib/python3.8/site-packages/elabapy/Manager.py", line 77, in get_status
    return self.send_req("status/")
  File "/root/.local/lib/python3.8/site-packages/elabapy/baseapi.py", line 80, in send_req
    req = requests_method(url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='tcbelab.com', port=443): Max retries exceeded with url: /login.php/api/v1/status/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7faf9c7e5580>: Failed to establish a new connection: [Errno 110] Connection timed out'))

I tried to launch it with and without certificate verification, tried different URLs, changing firewall rules, but all in vain.
Could you help me please to troubleshoot it?
ElabFTW: 4.2.1
OS: Ubuntu 20.04
Browser: Chrome 96.0.4664.45

**Comment by din14970** [comment]
Hey, thanks for checking out this project. I haven't made updates in a while so it might be that I need to update my code to accommodate the latest changes in elabapy. At least it's throwing a different kind of error which I am not checking for [here](https://github.com/din14970/elabftwqrprint/blob/ff95d52df5558d644559ca6c47e926bdccb91c1d/elabftwqrprint/configure_elabftw.py#L41) which is a bug. 

However, just from the trace it looks to me like you've provided an incorrect url. When it asks you for the url, you should only write `https://tcbelab.com`, it seems you also added `login.php` to it which will not work. Internally, the string `/api/v1/` is added to define the actual REST API endpoint: `https://tcbelab.com/api/v1/`. I see that your eLab instance is reachable via the browser on `https://tcbelab.com`, so that API endpoint should work with `verify=True` because it seems you are using a correctly signed SSL cert. Also be sure that you have a working token.

To check if your setup works, try to use the elabapy directly and see if this works from a python script or jupyter notebook:

```python
import elabapy

# initialize the manager with an endpoint and your token
manager = elabapy.Manager(endpoint="https://tcbelab.com/api/v1/", token="YOURTOKENHERE", verify=True)
manager.get_status()
```

See if this works. If not, you should pose your issue instead to [elabapy](https://github.com/elabftw/elabapy)

**Comment by ghost** [comment]
I'll check, thank you.
