### ISSUE TITLE
PIL Font Issue?

### ISSUE THREAD

**Issue by sailhobie** [din14970/elabftwqrprint#2]
I've been trying to get this working with my QL-800, and I think I am close, but I think it is a font issue.

Fresh install of ubuntu 20, able to acces elabFTW fine, and can print with brother_ql packge directly. just can't get the label to create.

any suggestions?

```
Traceback (most recent call last):
  File "/usr/local/bin/create_qr_sticker", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/elabftwqrprint/create_qr_sticker.py", line 289, in main
    background = create_qr_sticker_image(
  File "/usr/local/lib/python3.8/dist-packages/elabftwqrprint/create_qr_sticker.py", line 139, in create_qr_sticker_image
    font = ImageFont.truetype(font_path, font_size)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 642, in truetype
    return freetype(font)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 639, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 187, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by din14970** [comment]
Thanks for testing it out and making a bug report. I can reproduce this on Arch linux. The problem seems to be that the installation behaves differently on Linux and Mac OS; on Mac OS it works fine. For Linux, the scripts are placed in `~/.local/bin/` or `/usr/local/bin` after pip install. The former is not even on the path, so the scripts don't run. But even when adding this directory onto the path with `export PATH=$PATH:$HOME/.local/bin`, it doesn't work because on Linux it does not find the font file. 

The workaround I recommend at the moment: when you run a command, explicitly choose a font that the OS can find e.g. in /usr/share/fonts/TTF. For example `-d DejaVuSans.ttf` seems to work fine for me on Arch. If you really want the font I include in the repo, copy the Andale Mono.ttf file into that folder, then it works without the `-d` flag. 

Meanwhile I'll try to work out a more robust solution so that it works out of the box on Linux.

**Comment by sailhobie** [comment]
Excellent! both the -d flag and copying the .ttf file to a new folder /usr/share/fonts/TTF worked for me.

one issue I am working on is the size of the QR code. I am using the 12mm label stock so it is small to begin with, but the QR code is minuscule (about 1/3rd the available width).  Looks like it is the whitespace to the right b/c if I create the png, and print with brother_ql and rotate it fills the label space. Can I pass the rotate flag (-r) somehow?

also it would be nice to pass the --red flag so I can use the red/black label

```
--red                           Create a label to be printed on
                                  black/red/white tape (only with QL-8xx
                                  series on DK-22251 labels). You must use
                                  this option when printing on black/red tape,
                                  even when not printing red.
```

Thanks your help and creating this tool

**Comment by sailhobie** [comment]
Just tested creating a 62mm label and printing with --red flag via brother_ql using my other label stock. Definitely want to trim the extra whitepace and be able to rotate 90. Maybe even wordwrap to fit under the QR if possible?

**Comment by din14970** [comment]
The way I have my sticker image creation implemented (you can check in the ugly function that is ` create_qr_sticker_image` inside the `create_qr_sticker.py` file) is as follows (and is illustrated by this picture: <https://imgur.com/Jm2gRaA>):

1. I check the width and height in pixels of the sticker. If the width (in the direction of the roll of tape) is smaller than the height (the width of the roll of tape) I automatically rotate the image so that the maximum amount of stuff can be printed on the label.
2. I check whether short text needs to be added to the label. I want to have the possiblity of adding a short description underneath the QR code. For stickers created directly using the eLabFTW api with command `create_elab_sticker_item`, this short text is `<date> <entry title>`. I add the short description to the image and check its height.
3. The rest of the sticker height (which should now always be the minimum dimension) is filled with the QR code + a default whitespace border around the QR code which is required by the standard.
4. If there is long text, this fills in the space left to the right of the QR code and above the short description.

Now the thing is also that the label printer itself adds some padding to the labels. So if you are only printing QR codes with no text they may appear quite small. If you want the QR code to take up the maximum amount of space for your tape, for example on your 12 mm tape, you can try to reduce the border parameter with the `-b` flag and not use any text flags.

```
$ create_qr_sticker "the text I want to encode" -p 12 -b 0
```
Since I tried to write it so that the QR code always is the largest it can be, given the constraints of my "design", i'm not sure what a rotate flag would accomplish. Not sure if that helps you or if you found some other bug.

With respect to the `--red` flag, I didn't really have much of a usecase for it, and wouldn't know what I would want to have printed in red on my labels. Of course if you want more custom stickers, best to edit the images yourself and use brother_ql directly. My goal with this repo was to have a couple of easy scripts to quickly print standardized labels for my samples in my eLabFTW database.

**Comment by din14970** [comment]
ah maybe the issue is that endless tape prints differently (90 degrees rotated) compared to tape that is split into well defined stickers. I always want to maximize size of the labels so this should not happen with a flag, it should happen automatically. But this is something I couldn't know because I only have the 29x90 tape. Let's say you have an upright picture of a cat on your PC, and you print it with your brother ql, does it come out upright relative to the tape direction or upright relative to the width of the tape?

**Comment by sailhobie** [comment]
Ahhh that makes sense after looking at the design image, with the whitespace being for optional long text.

The rotate flag would be very useful when using narrow labels so that the long side of the image lines up with length of the tape. Are you using wide label tape? I could write a script as a workaround that would create the label and then call brother_ql with -r flag, but thought if the flags could be passed to brother_ql it might be as easy as getting the command line syntax right.

Another thought would be if people don't have long text called out it would switch to a more square design with the short text below. But that seems like it would be complicated and I don't want to pile feature requests on or anything, just happy to have something in the right direction.

WRT the red tape. I don't intend on printing anything in red for this application but it allows the printer to function with the red/black label tape. Otherwise the printer just errors out since the label tape doesn't match what is specified. Again, just thought if the flags were able to be passed through to brother_ql it might not require any code edits.

I'll look through the code and see if I can understand it  enough to drop in a flag. I'm just a hobbiest so we'll see how far I get haha

Thanks again for you work and support!

**Comment by sailhobie** [comment]
> ah maybe the issue is that endless tape prints differently (90 degrees rotated) compared to tape that is split into well defined stickers. I always want to maximize size of the labels so this should not happen with a flag, it should happen automatically. But this is something I couldn't know because I only have the 29x90 tape. Let's say you have an upright picture of a cat on your PC, and you print it with your brother ql, does it come out upright relative to the tape direction or upright relative to the width of the tape?

yes I am using continuous tape. The label design example prints across the width of the tape without the rotate flag. So with 12mm tape the long side is 12mm

Here is the 62mm example. I created image and then printed with brother_ql command since it is the red label tape, but same effect for the 12mm
https://i.imgur.com/RnPbWBO.jpg

**Comment by din14970** [comment]
> The label design example prints across the width of the tape without the rotate flag. So with 12mm tape the long side is 12mm

Ok then this should be a quick fix, basically whenever you have continuous tape, the picture should be rotated 90 degrees. The thing is that for the non-continuous tapes, you need the image to be the exact pixel dimensions or it doesn't work. And for the non-continuous tapes, the longest dimension of the image is along the length of the tape, so I based myself on that.

> The rotate flag would be very useful when using narrow labels so that the long side of the image lines up with length of the tape. Are you using wide label tape? 

The thing is exactly that I want this to happen automatically - the long side of the image should always align with the long side of the label.  It's just that I apparently have the wrong impression about how printing happens on the continuous tape. Will try to fix it today.

> Another thought would be if people don't have long text called out it would switch to a more square design with the short text below. 

This is actually what should happen, but with the continuous tape it's hard to guess how wide the sticker should be. You can check that

```
$ create_qr_sticker "the text I want to encode" -p 12
```

will actually produce a square image. However, when there is short text with endless tape it can get a bit buggy. I didn't bother too much with these details as I have the 29x90 tape. But since you have an interest in these continuous tapes I will look into it.

>WRT the red tape. I don't intend on printing anything in red for this application but it allows the printer to function with the red/black label tape. Otherwise the printer just errors out since the label tape doesn't match what is specified. Again, just thought if the flags were able to be passed through to brother_ql it might not require any code edits.

Didn't know that as I have the older QL-700 printer. Will see how best to fix that.

 > I'm just a hobbiest so we'll see how far I get haha

Also just a hobbiest ;)

**Comment by sailhobie** [comment]
Great! happy to test whatever you need.

I ran
`create_qr_sticker "the text I want to encode" -p 12`
and it did produce a square image. I then printed it with print_sticker function and it seemed appropriately sized on the label.

**Comment by sailhobie** [comment]
Was able to play around with it a bit to pass the rotate command and basically added 
`rotate: '90' `
to the printer configuration file, and added a line to the print command within print_sticker.py
```
    print_command = (
        f"brother_ql -b {print_conf['backend']} -m "
        f"{print_conf['printer']} -p {print_conf['identifyer']} "
        f"print -r {print_conf['rotate']} "
        f"{print_conf['labelsize']} {filename}"
```
Is a workaround for now.
_______________
also, creating a sticker with small border, -b 0, makes the qr big enough to read much better on the 12mm tape. I'm using small sample vials so looking to get label pretty small.

**Comment by din14970** [comment]
Great if that works for you, I'll try to patch it up in a more "robust" way for any potential future user. Make sure that you stick your QR codes on a flat surface and not on the curved surface of a cylindrical vial - at least when I tried it my phone could not interpret them.

**Comment by din14970** [comment]
I changed up the code quite a bit. Hope it works better now:

* The font issue should now be fixed also for Linux - it seems the issue was that the file was not included in the pip package because the initial file has a space in the name. I also tried to write it in a way so that file path issues will be avoided in the future.
* You can now manually rotate your image in two ways: rotating the image file with the `--rotate` flag which actually rotates the digital image on your computer, and through the `-m` option which behaves the same and is is fed directly to brother-ql print via its `-r` option (only affects how it is printed).
* The boolean printer configuration option `red_tape` is now available. You can re-run configure_printer or just add it manually.
* Instead of repeating all the argparse stuff in most of the scripts I tried to remove code duplication as much as possible, so now most options are directly available in all commands. In addition, I've changed the way the defaults work, so now you have some more control over them if you create an additional config file in the config folder (see the readme). 

I tested it briefly on my raspberry pi and it works as expected for me. Of course I can't test the printing process on the continuous tape. I will close out this issue because I believe at least the font issue is resolved, and I hope the other ones you mention in this thread also. If you run into another issue please open another issue.
